name: approle-test-v2

on:
  workflow_dispatch:

jobs:
  vault-test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch secret from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: http://host.docker.internal:8200
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            kv/data/demo foo | HELLO_SECRET
