name: test-vault-proxy
on:
  workflow_dispatch:

jobs:
  proxy-test:
    runs-on: self-hosted   # target your proxy runner via label if needed
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Curl via proxy (sanity)
        run: |
          echo "=== CURL START ==="
          # force IPv4 to avoid host.docker.internal IPv6 issues
          curl -4 -v --proxy http://host.docker.internal:8888 "$VAULT_HOST/v1/sys/health" || true
          echo "=== CURL END ==="
        env:
          VAULT_HOST: http://host.docker.internal:8200
          HTTP_PROXY: http://host.docker.internal:8888
          HTTPS_PROXY: http://host.docker.internal:8888

      - name: Vault Action with proxy
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: kv/data/demo FOO | DEMO_FOO
        env:
          # inject the same proxy envs (this mirrors the customer's job)
          HTTP_PROXY: http://host.docker.internal:8888
          HTTPS_PROXY: http://host.docker.internal:8888
          http_proxy: http://host.docker.internal:8888
          https_proxy: http://host.docker.internal:8888

      - name: Echo result
        run: |
          echo "DEMO_FOO='$DEMO_FOO'"
